%% Create and Train a Deep Learning Model
% Script for creating and training a deep learning network with the following 
% properties:
%%
% 
%  Number of layers: 13
%  Number of connections: 12
%  Training setup file: C:\Users\PC\Desktop\myCnnAdamDusukAgirlik.mat
%
%% 
% Run this script to create the network layers, import training and validation 
% data, and train the network. The network layers are stored in the workspace 
% variable |layers|. The trained network is stored in the workspace variable |net|.
% 
% To learn more, see <matlab:helpview('deeplearning','generate_matlab_code') 
% Generate MATLAB Code From Deep Network Designer>.
% 
% Auto-generated by MATLAB on 05-May-2024 21:25:38
%% Load Initial Parameters
% Load parameters for network initialization. For transfer learning, the network 
% initialization parameters are the parameters of the initial pretrained network.

trainingSetup = load("C:\Users\PC\Desktop\myCnnAdamDusukAgirlik.mat");
%% Import Data
% Import training and validation data.

imdsTrain = imageDatastore("C:\Users\PC\Desktop\Alzheimer_s Dataset\train","IncludeSubfolders",true,"LabelSource","foldernames");
[imdsTrain, imdsValidation] = splitEachLabel(imdsTrain,0.85,"randomized");

% Resize the images to match the network input layer.
augimdsTrain = augmentedImageDatastore([224 224 1],imdsTrain);
augimdsValidation = augmentedImageDatastore([224 224 1],imdsValidation);
%% Set Training Options
% Specify options to use when training.

opts = trainingOptions("adam",...
    "ExecutionEnvironment","auto",...
    "InitialLearnRate",0.0001,...
    "MaxEpochs",11,...
    "MiniBatchSize",32,...
    "Shuffle","every-epoch",...
    "Plots","training-progress",...
    "ValidationData",augimdsValidation);
%% Create Array of Layers

layers = [
    imageInputLayer([224 224 1],"Name","imageinput")
    convolution2dLayer([3 3],32,"Name","conv","Padding","same")
    maxPooling2dLayer([5 5],"Name","maxpool","Padding","same")
    reluLayer("Name","relu")
    convolution2dLayer([3 3],32,"Name","conv_1","Padding","same")
    maxPooling2dLayer([5 5],"Name","maxpool_1","Padding","same")
    reluLayer("Name","relu_1")
    convolution2dLayer([3 3],32,"Name","conv_2","Padding","same")
    maxPooling2dLayer([5 5],"Name","maxpool_2","Padding","same")
    reluLayer("Name","relu_2")
    fullyConnectedLayer(4,"Name","fc")
    softmaxLayer("Name","softmax")
    classificationLayer("Name","classoutput")];
%% Train Network
% Train the network using the specified options and training data.

[net, traininfo] = trainNetwork(augimdsTrain,layers,opts);